# ~/.config/starship.toml

# Makes prompt a single line
add_newline = false

[nodejs]
disabled = true

[line_break]
disabled = true

# Enable the Python module to display the active virtual environment managed by `uv`
[python]
disabled = false
# Customize the format to display the virtual environment
format = "ğŸ [$virtualenv]($style) "

# Disable the Conda module to prevent Conda environments from being displayed
[conda]
disabled = true

[gcloud]
format = ""

[git_status]

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_branch]
format = "[$branch]($style) "
truncation_length = 10

[git_commit]
commit_hash_length = 4
tag_symbol = "ğŸ”–"

[battery]
charging_symbol = "âš¡" # Corrected the charging symbol
discharging_symbol = "ğŸ”‹" 
full_symbol = "ğŸ”‹" 

[[battery.display]]
style = "bold red"
threshold = 30

[character]
error_symbol = "[âœ–](bold red) "

[cmd_duration]
format = " took [$duration]($style)" 
min_time = 10_000 # Show command duration over 10,000 milliseconds (=10 sec)

[hostname]
disabled = true
format = "<[$hostname]($style)>"
ssh_only = false
style = "bold dimmed white"
trim_at = "-"

[aws]
format = ''
style = 'bold blue'

[username]
show_always = false
style_user = "bold dimmed blue"

[directory]
truncation_length = 5
